name: React (Vite + TS) CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # allow manual trigger from GitHub UI

jobs:
  # ----------------------------------------------------
  # 1️⃣ Install dependencies (shared across jobs via cache)
  # ----------------------------------------------------
  setup:
    name: Setup & Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Persist node_modules and build artifacts for other jobs
      - name: Cache pnpm store
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  # ----------------------------------------------------
  # 2️⃣ Linting job
  # ----------------------------------------------------
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

  # ----------------------------------------------------
  # 3️⃣ Type checking
  # ----------------------------------------------------
  typecheck:
    name: Type Check (TS)
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Type Check
        run: pnpm run typecheck

  # ----------------------------------------------------
  # 4️⃣ Build job
  # ----------------------------------------------------
  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: [lint, typecheck]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build

  # ----------------------------------------------------
  # 5️⃣ Test job
  # ----------------------------------------------------
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm run test -- --run
